### ISSUE TITLE
It doesn't work if I change the expressions wrapper.

### ISSUE THREAD

**Issue by elantion** [tennisgent/angular-route-styles#18]
For some reasons I change the expressions wrapper to '{[{ }]}'. I think this is why I get a 404 error with {{ cssUrl }}. Can you tell me how to solve this problem? Thanks a lot!

**Comment by tennisgent** [comment]
@elantion: It won't work if you have changed your interpolation symbols using the `$interpolateProvider`. The template is hardcoded with some bindings to the default `{{` and `}}` symbols. If you want to use this with some other custom symbols, you would need to fork the repo and modify the source code to use whatever symbols you've chosen.  You would need to change line 17 of `route-styles.js` to the following:

```javascript
var html = '<link rel="stylesheet" ng-repeat="(routeCtrl, cssUrl) in routeStyles" ng-href="{[{cssUrl}]}" >';
```

However, I'll write up a quick change to `route-styles.js` that allows it to get the configured interpolation symbols by calling `$interpolate.startSymbol()` and $interpolate.endSymbol()` instead of just always assuming that it's using the default symbols. I'll try to get that fixed asap.

**Comment by elantion** [comment]
Thanks for your quick reply. I done as you said. It's working good for now. Looking forward your next version. Thank you again for making such a great project.

**Comment by tennisgent** [comment]
@elantion: Just fixed this issue with commit 11cbc54. Feel free to pull down the latest version and it should work for you without having to make any modifications.

**Comment by tennisgent** [comment]
Hopefully that works for you. If it doesn't, feel free to create another issue and we'll try to get it fixed.

**Comment by elantion** [comment]
It looks like have a syntax error at line 10

**Comment by elantion** [comment]
Without that error it working great! Thank you!

**Comment by tennisgent** [comment]
Good catch! My bad. It's fixed now.
